### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [wiseman/ardrone-browser-3d#1]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by wiseman** [comment]
This feels like spam (I got this exact message on multiple repos), and CPU & RAM are not critical issues for this project, so I'm closing.  Thanks for the suggestion, though.
